siren/police emoji dividers
area4lib/area4 pull request #300
Opened 2020-09-29 15:07 UTC by haliphax

## Description

Some dividers to kick off Hacktoberfest! #297

2020-09-29 15:09 UTC, haliphax commented
These only count October 1-31, so I guess I'll close this for now and reopen it in a couple of days. Cheers!

2020-10-01 17:18 UTC, RDIL requested changes
Unfortunately, at this time we aren't accepting dividers made up of more than one unique character.  If you were to change it to fit that criteria, I can merge, but right now I can't.  

Thank you!

2020-10-01 17:58 UTC, merged

2020-10-02 12:33 UTC, RDIL commented on area4/dividers.txt
> ->>>>>>>>>>>>
Whoops, I thought it was a conflict marker!  Thanks for noticing, I'll fix that.

2020-10-06 13:22 UTC, haliphax commented on area4/dividers.txt
> ->>>>>>>>>>>>
Ha! I did, too. My bad.